In [1]:
# Задание 3-4

In [2]:
#!pip install scikit-learn

In [3]:
import pandas as pd
import numpy as np
np.random.seed(42)

In [4]:
df = pd.read_csv("imports-85.data.csv")

In [5]:
df

symboling normalized-losses         make fuel-type aspiration  \
0            3                 ?  alfa-romero       gas        std   
1            3                 ?  alfa-romero       gas        std   
2            1                 ?  alfa-romero       gas        std   
3            2               164         audi       gas        std   
4            2               164         audi       gas        std   
..         ...               ...          ...       ...        ...   
200         -1                95        volvo       gas        std   
201         -1                95        volvo       gas      turbo   
202         -1                95        volvo       gas        std   
203         -1                95        volvo    diesel      turbo   
204         -1                95        volvo       gas      turbo   

    num-of-doors   body-style drive-wheels engine-location   wheel-base  ...  \
0            two  convertible          rwd           front         88.6  ...   
1            two  convertible          rwd           front         88.6  ...   
2            two    hatchback          rwd           front         94.5  ...   
3           four        sedan          fwd           front         99.8  ...   
4           four        sedan          4wd           front         99.4  ...   
..           ...          ...          ...             ...          ...  ...   
200         four        sedan          rwd           front        109.1  ...   
201         four        sedan          rwd           front        109.1  ...   
202         four        sedan          rwd           front        109.1  ...   
203         four        sedan          rwd           front        109.1  ...   
204         four        sedan          rwd           front        109.1  ...   

      fuel-system   bore   stroke   compression-ratio  horsepower  peak-rpm  \
0            mpfi   3.47     2.68                 9.0         111      5000   
1            mpfi   3.47     2.68                 9.0         111      5000   
2            mpfi   2.68     3.47                 9.0         154      5000   
3            mpfi   3.19     3.40                10.0         102      5500   
4            mpfi   3.19     3.40                 8.0         115      5500   
..            ...    ...      ...                 ...         ...       ...   
200          mpfi   3.78     3.15                 9.5         114      5400   
201          mpfi   3.78     3.15                 8.7         160      5300   
202          mpfi   3.58     2.87                 8.8         134      5500   
203           idi   3.01     3.40                23.0         106      4800   
204          mpfi   3.78     3.15                 9.5         114      5400   

      city-mpg  highway-mpg   price Unnamed: 26  
0           21           27   13495         NaN  
1           21           27   16500         NaN  
2           19           26   16500         NaN  
3           24           30   13950         NaN  
4           18           22   17450         NaN  
..         ...          ...     ...         ...  
200         23           28   16845         NaN  
201         19           25   19045         NaN  
202         18           23   21485         NaN  
203         26           27   22470         NaN  
204         19           25   22625         NaN  

[205 rows x 27 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   symboling           205 non-null    int64  
 1   normalized-losses   205 non-null    object 
 2   make                205 non-null    object 
 3   fuel-type           205 non-null    object 
 4   aspiration          205 non-null    object 
 5   num-of-doors        205 non-null    object 
 6   body-style          205 non-null    object 
 7   drive-wheels        205 non-null    object 
 8   engine-location     205 non-null    object 
 9    wheel-base         205 non-null    float64
 10   length             205 non-null    float64
 11   width              205 non-null    float64
 12   height             205 non-null    float64
 13   curb-weight        205 non-null    int64  
 14   engine-type        205 non-null    object 
 15   num-of-cylinders   205 non-null    object 
 16   engine-

In [8]:
df = df.drop(np.where(df['normalized-losses'] == "?")[0])
df = df.drop(np.where(df[' bore'] == "?")[0])
df = df.drop(np.where(df[' stroke'] == "?")[0])
df = df.drop(np.where(df['num-of-doors'] == "?")[0])

In [9]:
df

symboling normalized-losses   make fuel-type aspiration num-of-doors  \
3            2               164   audi       gas        std         four   
4            2               164   audi       gas        std         four   
6            1               158   audi       gas        std         four   
8            1               158   audi       gas      turbo         four   
10           2               192    bmw       gas        std          two   
..         ...               ...    ...       ...        ...          ...   
200         -1                95  volvo       gas        std         four   
201         -1                95  volvo       gas      turbo         four   
202         -1                95  volvo       gas        std         four   
203         -1                95  volvo    diesel      turbo         four   
204         -1                95  volvo       gas      turbo         four   

    body-style drive-wheels engine-location   wheel-base  ...   fuel-system  \
3        sedan          fwd           front         99.8  ...          mpfi   
4        sedan          4wd           front         99.4  ...          mpfi   
6        sedan          fwd           front        105.8  ...          mpfi   
8        sedan          fwd           front        105.8  ...          mpfi   
10       sedan          rwd           front        101.2  ...          mpfi   
..         ...          ...             ...          ...  ...           ...   
200      sedan          rwd           front        109.1  ...          mpfi   
201      sedan          rwd           front        109.1  ...          mpfi   
202      sedan          rwd           front        109.1  ...          mpfi   
203      sedan          rwd           front        109.1  ...           idi   
204      sedan          rwd           front        109.1  ...          mpfi   

      bore   stroke   compression-ratio  horsepower  peak-rpm   city-mpg  \
3     3.19     3.40                10.0         102      5500         24   
4     3.19     3.40                 8.0         115      5500         18   
6     3.19     3.40                 8.5         110      5500         19   
8     3.13     3.40                 8.3         140      5500         17   
10    3.50     2.80                 8.8         101      5800         23   
..     ...      ...                 ...         ...       ...        ...   
200   3.78     3.15                 9.5         114      5400         23   
201   3.78     3.15                 8.7         160      5300         19   
202   3.58     2.87                 8.8         134      5500         18   
203   3.01     3.40                23.0         106      4800         26   
204   3.78     3.15                 9.5         114      5400         19   

     highway-mpg   price Unnamed: 26  
3             30   13950         NaN  
4             22   17450         NaN  
6             25   17710         NaN  
8             20   23875         NaN  
10            29   16430         NaN  
..           ...     ...         ...  
200           28   16845         NaN  
201           25   19045         NaN  
202           23   21485         NaN  
203           27   22470         NaN  
204           25   22625         NaN  

[148 rows x 27 columns]

In [10]:
df.to_csv('imports-85.data_2.csv')

In [11]:
df = pd.read_csv("imports-85.data_2.csv")

In [12]:
df

Unnamed: 0  symboling  normalized-losses   make fuel-type aspiration  \
0             3          2                164   audi       gas        std   
1             4          2                164   audi       gas        std   
2             6          1                158   audi       gas        std   
3             8          1                158   audi       gas      turbo   
4            10          2                192    bmw       gas        std   
..          ...        ...                ...    ...       ...        ...   
143         200         -1                 95  volvo       gas        std   
144         201         -1                 95  volvo       gas      turbo   
145         202         -1                 95  volvo       gas        std   
146         203         -1                 95  volvo    diesel      turbo   
147         204         -1                 95  volvo       gas      turbo   

    num-of-doors body-style drive-wheels engine-location  ...   fuel-system  \
0           four      sedan          fwd           front  ...          mpfi   
1           four      sedan          4wd           front  ...          mpfi   
2           four      sedan          fwd           front  ...          mpfi   
3           four      sedan          fwd           front  ...          mpfi   
4            two      sedan          rwd           front  ...          mpfi   
..           ...        ...          ...             ...  ...           ...   
143         four      sedan          rwd           front  ...          mpfi   
144         four      sedan          rwd           front  ...          mpfi   
145         four      sedan          rwd           front  ...          mpfi   
146         four      sedan          rwd           front  ...           idi   
147         four      sedan          rwd           front  ...          mpfi   

      bore   stroke   compression-ratio   horsepower  peak-rpm  city-mpg  \
0     3.19     3.40                10.0          102      5500        24   
1     3.19     3.40                 8.0          115      5500        18   
2     3.19     3.40                 8.5          110      5500        19   
3     3.13     3.40                 8.3          140      5500        17   
4     3.50     2.80                 8.8          101      5800        23   
..     ...      ...                 ...          ...       ...       ...   
143   3.78     3.15                 9.5          114      5400        23   
144   3.78     3.15                 8.7          160      5300        19   
145   3.58     2.87                 8.8          134      5500        18   
146   3.01     3.40                23.0          106      4800        26   
147   3.78     3.15                 9.5          114      5400        19   

      highway-mpg   price Unnamed: 26  
0              30   13950         NaN  
1              22   17450         NaN  
2              25   17710         NaN  
3              20   23875         NaN  
4              29   16430         NaN  
..            ...     ...         ...  
143            28   16845         NaN  
144            25   19045         NaN  
145            23   21485         NaN  
146            27   22470         NaN  
147            25   22625         NaN  

[148 rows x 28 columns]

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Unnamed: 0          148 non-null    int64  
 1   symboling           148 non-null    int64  
 2   normalized-losses   148 non-null    int64  
 3   make                148 non-null    object 
 4   fuel-type           148 non-null    object 
 5   aspiration          148 non-null    object 
 6   num-of-doors        148 non-null    object 
 7   body-style          148 non-null    object 
 8   drive-wheels        148 non-null    object 
 9   engine-location     148 non-null    object 
 10   wheel-base         148 non-null    float64
 11   length             148 non-null    float64
 12   width              148 non-null    float64
 13   height             148 non-null    float64
 14   curb-weight        148 non-null    int64  
 15   engine-type        148 non-null    object 
 16   num-of-

In [14]:
df = pd.read_csv("imports-85.data_2.csv")
df_num = df.drop(['Unnamed: 0', 'make', 'fuel-type', 'aspiration',
                'num-of-doors', 'body-style',
                'drive-wheels', 'engine-location',
                ' engine-type', ' num-of-cylinders',
                ' fuel-system', ' bore', ' stroke', 'Unnamed: 26'], axis=1)

from sklearn.impute import SimpleImputer

imp = SimpleImputer(missing_values=np.nan, strategy="median")
imp.fit(df_num)
#imp.statistics_
X = imp.transform(df_num)
df_num = pd.DataFrame(X, columns=df_num.columns)
df_num.describe()

symboling  normalized-losses   wheel-base      length       width  \
count  148.000000         148.000000   148.000000  148.000000  148.000000   
mean     0.804054         123.418919    98.511486  173.324324   65.719595   
std      1.248993          36.366242     5.120713   10.892859    1.963291   
min     -2.000000          65.000000    88.400000  141.100000   60.300000   
25%      0.000000          94.000000    94.500000  166.300000   64.000000   
50%      1.000000         118.000000    97.100000  172.400000   65.400000   
75%      2.000000         150.000000   101.200000  180.650000   66.500000   
max      3.000000         256.000000   115.600000  202.600000   71.700000   

           height   curb-weight   engine-size   compression-ratio  \
count  148.000000    148.000000    148.000000          148.000000   
mean    53.826351   2488.932432    119.445946           10.256216   
std      2.310384    481.298763     31.672921            4.011589   
min     49.400000   1488.000000     61.000000            7.000000   
25%     52.000000   2121.500000     97.000000            8.700000   
50%     54.100000   2385.000000    109.000000            9.000000   
75%     55.550000   2844.750000    137.000000            9.400000   
max     59.800000   4066.000000    258.000000           23.000000   

        horsepower     peak-rpm    city-mpg   highway-mpg         price  
count   148.000000   148.000000  148.000000    148.000000    148.000000  
mean     97.297297  5083.108108   25.986486     31.608108  11781.520270  
std      31.167631   456.046082    6.081070      6.478258   5985.829944  
min      48.000000  4150.000000   15.000000     18.000000   5118.000000  
25%      69.000000  4800.000000   21.750000     27.000000   7607.500000  
50%      93.000000  5200.000000   26.000000     31.500000   9516.500000  
75%     115.250000  5425.000000   31.000000     37.000000  15656.250000  
max     200.000000  6600.000000   47.000000     53.000000  35056.000000

In [15]:
df_num

symboling  normalized-losses   wheel-base   length   width   height  \
0          2.0              164.0         99.8    176.6    66.2     54.3   
1          2.0              164.0         99.4    176.6    66.4     54.3   
2          1.0              158.0        105.8    192.7    71.4     55.7   
3          1.0              158.0        105.8    192.7    71.4     55.9   
4          2.0              192.0        101.2    176.8    64.8     54.3   
..         ...                ...          ...      ...     ...      ...   
143       -1.0               95.0        109.1    188.8    68.9     55.5   
144       -1.0               95.0        109.1    188.8    68.8     55.5   
145       -1.0               95.0        109.1    188.8    68.9     55.5   
146       -1.0               95.0        109.1    188.8    68.9     55.5   
147       -1.0               95.0        109.1    188.8    68.9     55.5   

      curb-weight   engine-size   compression-ratio   horsepower   peak-rpm  \
0          2337.0         109.0                10.0        102.0     5500.0   
1          2824.0         136.0                 8.0        115.0     5500.0   
2          2844.0         136.0                 8.5        110.0     5500.0   
3          3086.0         131.0                 8.3        140.0     5500.0   
4          2395.0         108.0                 8.8        101.0     5800.0   
..            ...           ...                 ...          ...        ...   
143        2952.0         141.0                 9.5        114.0     5400.0   
144        3049.0         141.0                 8.7        160.0     5300.0   
145        3012.0         173.0                 8.8        134.0     5500.0   
146        3217.0         145.0                23.0        106.0     4800.0   
147        3062.0         141.0                 9.5        114.0     5400.0   

      city-mpg   highway-mpg    price  
0         24.0          30.0  13950.0  
1         18.0          22.0  17450.0  
2         19.0          25.0  17710.0  
3         17.0          20.0  23875.0  
4         23.0          29.0  16430.0  
..         ...           ...      ...  
143       23.0          28.0  16845.0  
144       19.0          25.0  19045.0  
145       18.0          23.0  21485.0  
146       26.0          27.0  22470.0  
147       19.0          25.0  22625.0  

[148 rows x 14 columns]

In [16]:
"""
imp = SimpleImputer(missing_values=np.nan, strategy="median")
X = imp.fit_transform(df_num)
df_num = pd.DataFrame(X, columns=df_num.columns)
df_num.describe()
"""

'\nimp = SimpleImputer(missing_values=np.nan, strategy="median")\nX = imp.fit_transform(df_num)\ndf_num = pd.DataFrame(X, columns=df_num.columns)\ndf_num.describe()\n'

In [17]:
df_2 = pd.read_csv("imports-85.data_2.csv")
df_cat = df_2.drop(['Unnamed: 0', 'symboling', 'normalized-losses', ' wheel-base', ' length', 
                    ' width', ' height', ' curb-weight', ' engine-size', ' compression-ratio', 
                    ' horsepower', ' peak-rpm', ' city-mpg', ' highway-mpg', '  price', 'Unnamed: 26'], axis=1)

from sklearn.impute import SimpleImputer

imp = SimpleImputer(missing_values=np.nan, strategy="most_frequent")
imp.fit(df_cat)
X = imp.transform(df_cat)
df_cat = pd.DataFrame(X, columns=df_cat.columns)
df_cat.describe()

make fuel-type aspiration num-of-doors body-style drive-wheels  \
count      148       148        148          148        148          148   
unique      17         2          2            2          5            3   
top     toyota       gas        std         four      sedan          fwd   
freq        31       133        122           89         74           90   

       engine-location  engine-type  num-of-cylinders  fuel-system  bore  \
count              148          148               148          148   148   
unique               1            6                 6            5    31   
top              front          ohc              four         mpfi  3.62   
freq               148          108               121           64    20   

        stroke  
count      148  
unique      29  
top       3.03  
freq        14

In [18]:
df_cat

make fuel-type aspiration num-of-doors body-style drive-wheels  \
0     audi       gas        std         four      sedan          fwd   
1     audi       gas        std         four      sedan          4wd   
2     audi       gas        std         four      sedan          fwd   
3     audi       gas      turbo         four      sedan          fwd   
4      bmw       gas        std          two      sedan          rwd   
..     ...       ...        ...          ...        ...          ...   
143  volvo       gas        std         four      sedan          rwd   
144  volvo       gas      turbo         four      sedan          rwd   
145  volvo       gas        std         four      sedan          rwd   
146  volvo    diesel      turbo         four      sedan          rwd   
147  volvo       gas      turbo         four      sedan          rwd   

    engine-location  engine-type  num-of-cylinders  fuel-system  bore  stroke  
0             front          ohc              four         mpfi  3.19    3.40  
1             front          ohc              five         mpfi  3.19    3.40  
2             front          ohc              five         mpfi  3.19    3.40  
3             front          ohc              five         mpfi  3.13    3.40  
4             front          ohc              four         mpfi  3.50    2.80  
..              ...          ...               ...          ...   ...     ...  
143           front          ohc              four         mpfi  3.78    3.15  
144           front          ohc              four         mpfi  3.78    3.15  
145           front         ohcv               six         mpfi  3.58    2.87  
146           front          ohc               six          idi  3.01    3.40  
147           front          ohc              four         mpfi  3.78    3.15  

[148 rows x 12 columns]

In [19]:
new_df = pd.concat([df_num, df_cat], axis=1)

In [20]:
new_df

symboling  normalized-losses   wheel-base   length   width   height  \
0          2.0              164.0         99.8    176.6    66.2     54.3   
1          2.0              164.0         99.4    176.6    66.4     54.3   
2          1.0              158.0        105.8    192.7    71.4     55.7   
3          1.0              158.0        105.8    192.7    71.4     55.9   
4          2.0              192.0        101.2    176.8    64.8     54.3   
..         ...                ...          ...      ...     ...      ...   
143       -1.0               95.0        109.1    188.8    68.9     55.5   
144       -1.0               95.0        109.1    188.8    68.8     55.5   
145       -1.0               95.0        109.1    188.8    68.9     55.5   
146       -1.0               95.0        109.1    188.8    68.9     55.5   
147       -1.0               95.0        109.1    188.8    68.9     55.5   

      curb-weight   engine-size   compression-ratio   horsepower  ...  \
0          2337.0         109.0                10.0        102.0  ...   
1          2824.0         136.0                 8.0        115.0  ...   
2          2844.0         136.0                 8.5        110.0  ...   
3          3086.0         131.0                 8.3        140.0  ...   
4          2395.0         108.0                 8.8        101.0  ...   
..            ...           ...                 ...          ...  ...   
143        2952.0         141.0                 9.5        114.0  ...   
144        3049.0         141.0                 8.7        160.0  ...   
145        3012.0         173.0                 8.8        134.0  ...   
146        3217.0         145.0                23.0        106.0  ...   
147        3062.0         141.0                 9.5        114.0  ...   

     aspiration  num-of-doors  body-style  drive-wheels engine-location  \
0           std          four       sedan           fwd           front   
1           std          four       sedan           4wd           front   
2           std          four       sedan           fwd           front   
3         turbo          four       sedan           fwd           front   
4           std           two       sedan           rwd           front   
..          ...           ...         ...           ...             ...   
143         std          four       sedan           rwd           front   
144       turbo          four       sedan           rwd           front   
145         std          four       sedan           rwd           front   
146       turbo          four       sedan           rwd           front   
147       turbo          four       sedan           rwd           front   

     engine-type  num-of-cylinders  fuel-system  bore  stroke  
0            ohc              four         mpfi  3.19    3.40  
1            ohc              five         mpfi  3.19    3.40  
2            ohc              five         mpfi  3.19    3.40  
3            ohc              five         mpfi  3.13    3.40  
4            ohc              four         mpfi  3.50    2.80  
..           ...               ...          ...   ...     ...  
143          ohc              four         mpfi  3.78    3.15  
144          ohc              four         mpfi  3.78    3.15  
145         ohcv               six         mpfi  3.58    2.87  
146          ohc               six          idi  3.01    3.40  
147          ohc              four         mpfi  3.78    3.15  

[148 rows x 26 columns]

In [21]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   symboling           148 non-null    float64
 1   normalized-losses   148 non-null    float64
 2    wheel-base         148 non-null    float64
 3    length             148 non-null    float64
 4    width              148 non-null    float64
 5    height             148 non-null    float64
 6    curb-weight        148 non-null    float64
 7    engine-size        148 non-null    float64
 8    compression-ratio  148 non-null    float64
 9    horsepower         148 non-null    float64
 10   peak-rpm           148 non-null    float64
 11   city-mpg           148 non-null    float64
 12   highway-mpg        148 non-null    float64
 13    price             148 non-null    float64
 14  make                148 non-null    object 
 15  fuel-type           148 non-null    object 
 16  aspirati

In [22]:
new_df.to_csv('cars_imputed.csv')

In [23]:
df = pd.read_csv("cars_imputed.csv")

In [24]:
df = df.drop(['Unnamed: 0'], axis=1)

In [25]:
df

symboling  normalized-losses   wheel-base   length   width   height  \
0          2.0              164.0         99.8    176.6    66.2     54.3   
1          2.0              164.0         99.4    176.6    66.4     54.3   
2          1.0              158.0        105.8    192.7    71.4     55.7   
3          1.0              158.0        105.8    192.7    71.4     55.9   
4          2.0              192.0        101.2    176.8    64.8     54.3   
..         ...                ...          ...      ...     ...      ...   
143       -1.0               95.0        109.1    188.8    68.9     55.5   
144       -1.0               95.0        109.1    188.8    68.8     55.5   
145       -1.0               95.0        109.1    188.8    68.9     55.5   
146       -1.0               95.0        109.1    188.8    68.9     55.5   
147       -1.0               95.0        109.1    188.8    68.9     55.5   

      curb-weight   engine-size   compression-ratio   horsepower  ...  \
0          2337.0         109.0                10.0        102.0  ...   
1          2824.0         136.0                 8.0        115.0  ...   
2          2844.0         136.0                 8.5        110.0  ...   
3          3086.0         131.0                 8.3        140.0  ...   
4          2395.0         108.0                 8.8        101.0  ...   
..            ...           ...                 ...          ...  ...   
143        2952.0         141.0                 9.5        114.0  ...   
144        3049.0         141.0                 8.7        160.0  ...   
145        3012.0         173.0                 8.8        134.0  ...   
146        3217.0         145.0                23.0        106.0  ...   
147        3062.0         141.0                 9.5        114.0  ...   

     aspiration  num-of-doors  body-style  drive-wheels engine-location  \
0           std          four       sedan           fwd           front   
1           std          four       sedan           4wd           front   
2           std          four       sedan           fwd           front   
3         turbo          four       sedan           fwd           front   
4           std           two       sedan           rwd           front   
..          ...           ...         ...           ...             ...   
143         std          four       sedan           rwd           front   
144       turbo          four       sedan           rwd           front   
145         std          four       sedan           rwd           front   
146       turbo          four       sedan           rwd           front   
147       turbo          four       sedan           rwd           front   

     engine-type  num-of-cylinders  fuel-system  bore  stroke  
0            ohc              four         mpfi  3.19    3.40  
1            ohc              five         mpfi  3.19    3.40  
2            ohc              five         mpfi  3.19    3.40  
3            ohc              five         mpfi  3.13    3.40  
4            ohc              four         mpfi  3.50    2.80  
..           ...               ...          ...   ...     ...  
143          ohc              four         mpfi  3.78    3.15  
144          ohc              four         mpfi  3.78    3.15  
145         ohcv               six         mpfi  3.58    2.87  
146          ohc               six          idi  3.01    3.40  
147          ohc              four         mpfi  3.78    3.15  

[148 rows x 26 columns]

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   symboling           148 non-null    float64
 1   normalized-losses   148 non-null    float64
 2    wheel-base         148 non-null    float64
 3    length             148 non-null    float64
 4    width              148 non-null    float64
 5    height             148 non-null    float64
 6    curb-weight        148 non-null    float64
 7    engine-size        148 non-null    float64
 8    compression-ratio  148 non-null    float64
 9    horsepower         148 non-null    float64
 10   peak-rpm           148 non-null    float64
 11   city-mpg           148 non-null    float64
 12   highway-mpg        148 non-null    float64
 13    price             148 non-null    float64
 14  make                148 non-null    object 
 15  fuel-type           148 non-null    object 
 16  aspirati

In [27]:
df = pd.read_csv("cars_imputed.csv")
df_cat = df['make']
df_cat_encoded, df_categories = df_cat.factorize()
df_cat_encoded

array([ 0,  0,  0,  0,  1,  1,  1,  1,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,
        6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,
        9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 11, 12, 12, 12, 12, 12,
       12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14,
       14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
       14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15,
       15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16], dtype=int64)

In [28]:
df_categories

Index(['audi', 'bmw', 'chevrolet', 'dodge', 'jaguar', 'mazda', 'mercedes-benz',
       'mitsubishi', 'nissan', 'peugot', 'plymouth', 'porsche', 'saab',
       'subaru', 'toyota', 'volkswagen', 'volvo'],
      dtype='object')

In [29]:
df['make'] = df_cat_encoded
df[df_num.columns] = df_num

In [30]:
df_cat = df['fuel-type']
df_cat_encoded, df_categories = df_cat.factorize()
df_cat_encoded

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [31]:
df_categories

Index(['gas', 'diesel'], dtype='object')

In [32]:
df['fuel-type'] = df_cat_encoded
df[df_num.columns] = df_num

In [33]:
df_cat = df['aspiration']
df_cat_encoded, df_categories = df_cat.factorize()
df_cat_encoded

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1], dtype=int64)

In [34]:
df_categories

Index(['std', 'turbo'], dtype='object')

In [35]:
df['aspiration'] = df_cat_encoded
df[df_num.columns] = df_num

In [36]:
df_cat = df['num-of-doors']
df_cat_encoded, df_categories = df_cat.factorize()
df_cat_encoded

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [37]:
df_categories

Index(['four', 'two'], dtype='object')

In [38]:
df['num-of-doors'] = df_cat_encoded
df[df_num.columns] = df_num

In [39]:
df_cat = df['body-style']
df_cat_encoded, df_categories = df_cat.factorize()
df_cat_encoded

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 2, 3, 0, 4, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 3, 1, 0, 0, 2, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 2, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 3, 3, 1, 3, 1, 4, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0], dtype=int64)

In [40]:
df_categories

Index(['sedan', 'hatchback', 'wagon', 'hardtop', 'convertible'], dtype='object')

In [41]:
df['body-style'] = df_cat_encoded
df[df_num.columns] = df_num

In [42]:
df_cat = df['drive-wheels']
df_cat_encoded, df_categories = df_cat.factorize()
df_cat_encoded

array([0, 1, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
       0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [43]:
df_categories

Index(['fwd', '4wd', 'rwd'], dtype='object')

In [44]:
df['drive-wheels'] = df_cat_encoded
df[df_num.columns] = df_num

In [45]:
df_cat = df['engine-location']
df_cat_encoded, df_categories = df_cat.factorize()
df_cat_encoded

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [46]:
df_categories

Index(['front'], dtype='object')

In [47]:
df['engine-location'] = df_cat_encoded
df[df_num.columns] = df_num

In [48]:
df_cat = df[' engine-type']
df_cat_encoded, df_categories = df_cat.factorize()
df_cat_encoded

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
       0, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0], dtype=int64)

In [49]:
df_categories

Index(['ohc', 'l', 'dohc', 'rotor', 'ohcv', 'ohcf'], dtype='object')

In [50]:
df[' engine-type'] = df_cat_encoded
df[df_num.columns] = df_num

In [51]:
df_cat = df[' num-of-cylinders']
df_cat_encoded, df_categories = df_cat.factorize()
df_cat_encoded

array([0, 1, 1, 1, 0, 0, 2, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
       0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 5, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0], dtype=int64)

In [52]:
df_categories

Index(['four', 'five', 'six', 'three', 'two', 'eight'], dtype='object')

In [53]:
df[' num-of-cylinders'] = df_cat_encoded
df[df_num.columns] = df_num

In [54]:
df_cat = df[' fuel-system']
df_cat_encoded, df_categories = df_cat.factorize()
df_cat_encoded

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 2, 2, 2, 0, 1, 1, 1, 1, 1, 0, 3, 3, 3, 3, 0, 1, 1, 1, 4, 4, 1,
       1, 1, 4, 4, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 3, 0, 3, 0, 3, 0, 1, 4, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 3, 0, 3,
       0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0], dtype=int64)

In [55]:
df_categories

Index(['mpfi', '2bbl', '4bbl', 'idi', 'spdi'], dtype='object')

In [56]:
df[' fuel-system'] = df_cat_encoded
df[df_num.columns] = df_num

In [57]:
df_cat = df[' bore']
df_cat_encoded, df_categories = df_cat.factorize()
df_cat_encoded

array([ 0,  0,  0,  1,  2,  2,  3,  3,  4,  5,  5,  6,  6,  5,  6,  6,  6,
        7,  5,  5,  5,  5,  8,  9,  9,  9,  9, 10, 10, 10, 10, 10, 11, 12,
       12, 12, 12, 13,  6,  6,  6,  5, 14, 15, 15, 15, 14, 14, 16, 17, 16,
       16, 16, 16, 16, 16, 16, 16, 18, 18, 19, 19, 19, 19, 19, 19, 13, 20,
       13, 20, 13, 20, 21,  6,  5,  6,  6,  6, 15, 22, 23, 23, 24, 23, 23,
       23, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26,
       26, 26,  0,  0, 27, 27,  0,  0,  0,  0,  0, 28, 28, 25, 25, 25, 25,
       25, 25,  3, 27,  3,  3,  3, 27, 27, 27, 29,  0, 29,  0,  0, 29,  0,
        0, 30, 30, 30, 30, 25, 25, 30, 30, 12, 29, 30], dtype=int64)

In [58]:
df_categories

Index(['3.19', '3.13', '3.50', '3.31', '2.91', '3.03', '2.97', '3.63', '3.08',
       '?', '3.39', '3.76', '3.58', '3.46', '3.17', '3.35', '3.15', '2.99',
       '3.33', '3.43', '3.70', '3.61', '3.94', '3.54', '2.54', '3.62', '3.05',
       '3.27', '3.24', '3.01', '3.78'],
      dtype='object')

In [59]:
df[' bore'] = df_cat_encoded
df[df_num.columns] = df_num

In [60]:
df_cat = df[' stroke']
df_cat_encoded, df_categories = df_cat.factorize()
df_cat_encoded

array([ 0,  0,  0,  0,  1,  1,  2,  2,  3,  4,  4,  5,  5,  6,  5,  5,  5,
        7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  6,  6,  6,  6,  6, 10, 11,
       11, 11, 11, 12,  5,  5,  5,  6, 13, 13, 13, 13, 13, 13, 14, 15, 14,
       14, 14, 14, 14, 14, 14, 14, 15, 15, 16, 16, 16, 16, 16, 16,  2, 17,
       18, 17,  2, 17, 19,  5,  6,  5,  5,  5, 13,  4, 20, 20, 21, 20, 20,
       20, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,  3,  3,  3,  3,
        3,  3,  3,  3, 24, 24,  3,  3,  3,  3,  3, 25, 25, 26, 26, 26, 26,
       26, 26, 27, 24, 27, 27, 27, 24, 24, 24,  0,  0,  0,  0,  0,  0,  0,
        0,  8,  8,  8,  8,  8,  8,  8,  8, 28,  0,  8], dtype=int64)

In [61]:
df_categories

Index(['3.40', '2.80', '3.19', '3.03', '3.11', '3.23', '3.39', '4.17', '3.15',
       '?', '3.16', '3.64', '3.10', '3.46', '3.29', '3.47', '3.27', '3.52',
       '2.19', '3.21', '3.07', '2.07', '2.36', '2.64', '3.35', '3.08', '3.50',
       '3.54', '2.87'],
      dtype='object')

In [62]:
df[' stroke'] = df_cat_encoded
df[df_num.columns] = df_num

In [63]:
df = df.drop(['Unnamed: 0'], axis=1)

In [64]:
df

symboling  normalized-losses   wheel-base   length   width   height  \
0          2.0              164.0         99.8    176.6    66.2     54.3   
1          2.0              164.0         99.4    176.6    66.4     54.3   
2          1.0              158.0        105.8    192.7    71.4     55.7   
3          1.0              158.0        105.8    192.7    71.4     55.9   
4          2.0              192.0        101.2    176.8    64.8     54.3   
..         ...                ...          ...      ...     ...      ...   
143       -1.0               95.0        109.1    188.8    68.9     55.5   
144       -1.0               95.0        109.1    188.8    68.8     55.5   
145       -1.0               95.0        109.1    188.8    68.9     55.5   
146       -1.0               95.0        109.1    188.8    68.9     55.5   
147       -1.0               95.0        109.1    188.8    68.9     55.5   

      curb-weight   engine-size   compression-ratio   horsepower  ...  \
0          2337.0         109.0                10.0        102.0  ...   
1          2824.0         136.0                 8.0        115.0  ...   
2          2844.0         136.0                 8.5        110.0  ...   
3          3086.0         131.0                 8.3        140.0  ...   
4          2395.0         108.0                 8.8        101.0  ...   
..            ...           ...                 ...          ...  ...   
143        2952.0         141.0                 9.5        114.0  ...   
144        3049.0         141.0                 8.7        160.0  ...   
145        3012.0         173.0                 8.8        134.0  ...   
146        3217.0         145.0                23.0        106.0  ...   
147        3062.0         141.0                 9.5        114.0  ...   

     aspiration  num-of-doors  body-style  drive-wheels  engine-location  \
0             0             0           0             0                0   
1             0             0           0             1                0   
2             0             0           0             0                0   
3             1             0           0             0                0   
4             0             1           0             2                0   
..          ...           ...         ...           ...              ...   
143           0             0           0             2                0   
144           1             0           0             2                0   
145           0             0           0             2                0   
146           1             0           0             2                0   
147           1             0           0             2                0   

      engine-type   num-of-cylinders   fuel-system   bore   stroke  
0               0                  0             0      0        0  
1               0                  1             0      0        0  
2               0                  1             0      0        0  
3               0                  1             0      1        0  
4               0                  0             0      2        1  
..            ...                ...           ...    ...      ...  
143             0                  0             0     30        8  
144             0                  0             0     30        8  
145             4                  2             0     12       28  
146             0                  2             3     29        0  
147             0                  0             0     30        8  

[148 rows x 26 columns]

In [65]:
from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(df, test_size=0.35, random_state=42)
train_set.head(5)

symboling  normalized-losses   wheel-base   length   width   height  \
40        2.0              161.0         93.7    157.3    64.4     50.8   
60        0.0              128.0        100.4    181.7    66.5     55.1   
24        3.0              150.0         95.3    169.0    65.7     49.6   
25        3.0              150.0         95.3    169.0    65.7     49.6   
23        3.0              150.0         95.3    169.0    65.7     49.6   

     curb-weight   engine-size   compression-ratio   horsepower  ...  \
40        2004.0          92.0                 9.4         68.0  ...   
60        3095.0         181.0                 9.0        152.0  ...   
24        2380.0          70.0                 9.4        101.0  ...   
25        2385.0          70.0                 9.4        101.0  ...   
23        2380.0          70.0                 9.4        101.0  ...   

    aspiration  num-of-doors  body-style  drive-wheels  engine-location  \
40           0             1           1             0                0   
60           0             0           0             0                0   
24           0             1           1             2                0   
25           0             1           1             2                0   
23           0             1           1             2                0   

     engine-type   num-of-cylinders   fuel-system   bore   stroke  
40             0                  0             1      6        5  
60             4                  2             0     19       16  
24             3                  4             2      9        9  
25             3                  4             2      9        9  
23             3                  4             2      9        9  

[5 rows x 26 columns]

In [66]:
df.columns

Index(['symboling', 'normalized-losses', ' wheel-base', ' length', ' width',
       ' height', ' curb-weight', ' engine-size', ' compression-ratio',
       ' horsepower', ' peak-rpm', ' city-mpg', ' highway-mpg', '  price',
       'make', 'fuel-type', 'aspiration', 'num-of-doors', 'body-style',
       'drive-wheels', 'engine-location', ' engine-type', ' num-of-cylinders',
       ' fuel-system', ' bore', ' stroke'],
      dtype='object')

In [67]:
Xs = ['normalized-losses', 'make', 'fuel-type', 'aspiration', 'num-of-doors', 'body-style', 'drive-wheels',
      'engine-location', ' wheel-base', ' length', ' width', ' height', ' curb-weight', ' engine-type',
      ' num-of-cylinders', ' engine-size', ' fuel-system', ' bore', ' stroke', ' compression-ratio',
      ' horsepower', ' peak-rpm', ' city-mpg', ' highway-mpg', '  price']
Ys = ['symboling']
Xs

['normalized-losses',
 'make',
 'fuel-type',
 'aspiration',
 'num-of-doors',
 'body-style',
 'drive-wheels',
 'engine-location',
 ' wheel-base',
 ' length',
 ' width',
 ' height',
 ' curb-weight',
 ' engine-type',
 ' num-of-cylinders',
 ' engine-size',
 ' fuel-system',
 ' bore',
 ' stroke',
 ' compression-ratio',
 ' horsepower',
 ' peak-rpm',
 ' city-mpg',
 ' highway-mpg',
 '  price']

In [68]:
train_Xs = train_set[Xs]
train_Ys = train_set[Ys]

test_Xs = test_set[Xs]
test_Ys = test_set[Ys]

In [69]:
def MAE(Ys_real, Ys_predict):
    Losses = np.abs(Ys_real - Ys_predict)
    m = len(Ys_real)
    cost_result = 1 / m * np.sum(Losses)
    return cost_result

In [70]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(train_Xs, train_Ys)
predictions = model.predict(train_Xs)
#print("coef:", model.coef_, "; intercept:", model.intercept_)
print("MAE train:", MAE(train_Ys, predictions))

MAE train: symboling    0.452881
dtype: float64


In [71]:
predictions = model.predict(test_Xs)
print("MAE test:", MAE(test_Ys, predictions))

MAE test: symboling    0.666597
dtype: float64


In [72]:
# Используя подход факторизации категориальных признаков мы увеличили точность модели (уменьшив показатели MAE train и MAE test).