In [1]:
#!pip install torch

In [2]:
import torch
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import numpy as np

In [3]:
torch.tensor([[1, 2, 3, 4]])

tensor([[1, 2, 3, 4]])

In [4]:
torch.tensor([[1, 2], [3, 4]])

tensor([[1, 2],
        [3, 4]])

In [5]:
#torch.tensor([[1, 2], [3, 4]], )

In [6]:
tensor_number = torch.tensor(1)
print(tensor_number)

tensor_float = torch.tensor(1.0, dtype=torch.float64)
print(tensor_float)

tensor_1d = torch.tensor([1, 2, 3])
print(tensor_1d)

np_array = np.array([[4, 3], [2, 1]])
tensor_from_np = torch.tensor(np_array)
print(tensor_from_np)

print(torch.exp(tensor_from_np))
print(torch.log(tensor_from_np))
print(torch.sqrt(tensor_1d))
print(tensor_1d.shape)
print(np_array.shape)
print(tensor_from_np.shape)

tensor(1)
tensor(1., dtype=torch.float64)
tensor([1, 2, 3])
tensor([[4, 3],
        [2, 1]], dtype=torch.int32)
tensor([[54.5981, 20.0855],
        [ 7.3891,  2.7183]])
tensor([[1.3863, 1.0986],
        [0.6931, 0.0000]])
tensor([1.0000, 1.4142, 1.7321])
torch.Size([3])
(2, 2)
torch.Size([2, 2])


In [7]:
x = torch.tensor(1.0, requires_grad=True)
y = torch.tensor(2.0, requires_grad=True)
z = torch.tensor(3.0, requires_grad=True)

f = 4 * y * torch.sqrt(x) + 2 * torch.log(z)
f.backward()
print(x.grad, y.grad, z.grad)

tensor(4.) tensor(4.) tensor(0.6667)


In [8]:
x = torch.tensor(-2.0, requires_grad=True)
y = torch.tensor(5.0, requires_grad=True)
z = torch.tensor(-4.0, requires_grad=True)

f = (x + y) * z
f.backward()
print(x.grad, y.grad, z.grad)

tensor(-4.) tensor(-4.) tensor(3.)


In [9]:
trainset = datasets.MNIST('Datasets', download=True, train=True, transform=transforms.ToTensor())
testset = datasets.MNIST('Datasets', download=True, train=False, transform=transforms.ToTensor())

trainloader = DataLoader(trainset, shuffle=True)
testloader = DataLoader(testset, shuffle=True)

C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\datasets\mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [10]:
import torch.nn as nn

class SimpleNN():
    def __init__(self):
        self.W_1 = torch.rand(2, 4, requires_grad=True)
        self.b_1 = torch.rand(1, 4, requires_grad=True)

        self.W_2 = torch.rand(4, 1, requires_grad=True)
        self.b_2 = torch.rand(1, 1, requires_grad=True)
        
        self.loss = nn.BCELoss()
        
    def train(self, Xs, Ys):
        for idx, X in enumerate(Xs):
            Y_hat = self.predict(X).view(-1)
            Y = Ys[idx]
            
            pred = self.loss(Y_hat, Y)
            pred.backward()

            #print("Loss: ", pred)
        #print("End of train")
            
    def predict(self, X):
        Z_1 = torch.matmul(X, self.W_1) + self.b_1
        A_1 = torch.sigmoid(Z_1)
        
        Z_2 = torch.matmul(A_1, self.W_2) + self.b_2
        A_2 = torch.sigmoid(Z_2)
        return A_2

Xs = torch.tensor([
    [3, 2],
    [4, -1],
    [2, 5],
    [6, -2]
], dtype=torch.float32)

Ys = torch.tensor([[1, 1, 0, 0]], dtype=torch.float32)
Ys = Ys.reshape(-1, 1) 

nn = SimpleNN()

for i in range(1, 5+1):
    #print(f"Epoc {i}")
    nn.train(Xs, Ys)
    
for idx, X in enumerate(Xs):
    print("Predicted: ", nn.predict(X), "\nTrue", Ys[idx], "\n")


#pred = nn.predict(Xs[0, :])
#print(pred)
#Xs.shape

Predicted:  tensor([[0.7293]], grad_fn=<SigmoidBackward>) 
True tensor([1.]) 

Predicted:  tensor([[0.7236]], grad_fn=<SigmoidBackward>) 
True tensor([1.]) 

Predicted:  tensor([[0.7341]], grad_fn=<SigmoidBackward>) 
True tensor([0.]) 

Predicted:  tensor([[0.7275]], grad_fn=<SigmoidBackward>) 
True tensor([0.]) 

